/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;
import javax.swing.JPanel;
import paneles.CambiaPanel;

/**
 *
 * @author Cliente
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.UNO.setSelected(true);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        pnlMenu = new javax.swing.JPanel();
        DOS = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UNO = new rsbuttom.RSButtonMetro();
        CINCO = new rsbuttom.RSButtonMetro();
        TRES = new rsbuttom.RSButtonMetro();
        CUATRO = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        OCHO = new rsbuttom.RSButtonMetro();
        SIETE = new rsbuttom.RSButtonMetro();
        SEIS = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setColorHover(new java.awt.Color(0, 51, 204));
        btnMenu.setColorNormal(new java.awt.Color(0, 51, 204));
        btnMenu.setColorPressed(new java.awt.Color(0, 51, 204));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(214, 217, 223));

        DOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        DOS.setText("COLLECTION");
        DOS.setColorHover(new java.awt.Color(204, 204, 204));
        DOS.setColorNormal(new java.awt.Color(214, 217, 223));
        DOS.setColorPressed(new java.awt.Color(204, 204, 204));
        DOS.setColorTextHover(new java.awt.Color(128, 128, 131));
        DOS.setColorTextNormal(new java.awt.Color(128, 128, 131));
        DOS.setColorTextPressed(new java.awt.Color(128, 128, 131));
        DOS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DOS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DOS.setIconTextGap(25);
        DOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DOSMousePressed(evt);
            }
        });
        DOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOSActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("PEOPLE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UNO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        UNO.setText("HOME");
        UNO.setColorHover(new java.awt.Color(166, 166, 166));
        UNO.setColorNormal(new java.awt.Color(204, 204, 204));
        UNO.setColorPressed(new java.awt.Color(204, 204, 204));
        UNO.setColorTextHover(new java.awt.Color(128, 128, 131));
        UNO.setColorTextNormal(new java.awt.Color(128, 128, 131));
        UNO.setColorTextPressed(new java.awt.Color(128, 128, 131));
        UNO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UNO.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        UNO.setIconTextGap(25);
        UNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UNOMousePressed(evt);
            }
        });
        UNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNOActionPerformed(evt);
            }
        });

        CINCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        CINCO.setText("MARKET");
        CINCO.setColorHover(new java.awt.Color(204, 204, 204));
        CINCO.setColorNormal(new java.awt.Color(214, 217, 223));
        CINCO.setColorPressed(new java.awt.Color(204, 204, 204));
        CINCO.setColorTextHover(new java.awt.Color(128, 128, 131));
        CINCO.setColorTextNormal(new java.awt.Color(128, 128, 131));
        CINCO.setColorTextPressed(new java.awt.Color(128, 128, 131));
        CINCO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CINCO.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CINCO.setIconTextGap(25);
        CINCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CINCOMousePressed(evt);
            }
        });
        CINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CINCOActionPerformed(evt);
            }
        });

        TRES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        TRES.setText("FEEDBACK");
        TRES.setColorHover(new java.awt.Color(204, 204, 204));
        TRES.setColorNormal(new java.awt.Color(214, 217, 223));
        TRES.setColorPressed(new java.awt.Color(204, 204, 204));
        TRES.setColorTextHover(new java.awt.Color(128, 128, 131));
        TRES.setColorTextNormal(new java.awt.Color(128, 128, 131));
        TRES.setColorTextPressed(new java.awt.Color(128, 128, 131));
        TRES.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TRES.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        TRES.setIconTextGap(25);
        TRES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TRESMousePressed(evt);
            }
        });
        TRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRESActionPerformed(evt);
            }
        });

        CUATRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        CUATRO.setText("CHAT");
        CUATRO.setColorHover(new java.awt.Color(204, 204, 204));
        CUATRO.setColorNormal(new java.awt.Color(214, 217, 223));
        CUATRO.setColorPressed(new java.awt.Color(204, 204, 204));
        CUATRO.setColorTextHover(new java.awt.Color(128, 128, 131));
        CUATRO.setColorTextNormal(new java.awt.Color(128, 128, 131));
        CUATRO.setColorTextPressed(new java.awt.Color(128, 128, 131));
        CUATRO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CUATRO.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CUATRO.setIconTextGap(25);
        CUATRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CUATROMousePressed(evt);
            }
        });
        CUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUATROActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(214, 217, 223));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 128, 131));
        jLabel2.setText("DEVICE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        OCHO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        OCHO.setText("WEB");
        OCHO.setColorHover(new java.awt.Color(204, 204, 204));
        OCHO.setColorNormal(new java.awt.Color(214, 217, 223));
        OCHO.setColorPressed(new java.awt.Color(204, 204, 204));
        OCHO.setColorTextHover(new java.awt.Color(128, 128, 131));
        OCHO.setColorTextNormal(new java.awt.Color(128, 128, 131));
        OCHO.setColorTextPressed(new java.awt.Color(128, 128, 131));
        OCHO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OCHO.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        OCHO.setIconTextGap(25);
        OCHO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OCHOMousePressed(evt);
            }
        });
        OCHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCHOActionPerformed(evt);
            }
        });

        SIETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        SIETE.setText("IOS");
        SIETE.setColorHover(new java.awt.Color(204, 204, 204));
        SIETE.setColorNormal(new java.awt.Color(214, 217, 223));
        SIETE.setColorPressed(new java.awt.Color(204, 204, 204));
        SIETE.setColorTextHover(new java.awt.Color(128, 128, 131));
        SIETE.setColorTextNormal(new java.awt.Color(128, 128, 131));
        SIETE.setColorTextPressed(new java.awt.Color(128, 128, 131));
        SIETE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SIETE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SIETE.setIconTextGap(25);
        SIETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SIETEMousePressed(evt);
            }
        });
        SIETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIETEActionPerformed(evt);
            }
        });

        SEIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        SEIS.setText("ANDROID");
        SEIS.setColorHover(new java.awt.Color(204, 204, 204));
        SEIS.setColorNormal(new java.awt.Color(214, 217, 223));
        SEIS.setColorPressed(new java.awt.Color(204, 204, 204));
        SEIS.setColorTextHover(new java.awt.Color(128, 128, 131));
        SEIS.setColorTextNormal(new java.awt.Color(128, 128, 131));
        SEIS.setColorTextPressed(new java.awt.Color(128, 128, 131));
        SEIS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SEIS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        SEIS.setIconTextGap(25);
        SEIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SEISMousePressed(evt);
            }
        });
        SEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEISActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DOS, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(UNO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TRES, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(CUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(CINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(OCHO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(DOS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UNO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(TRES, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(SEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OCHO, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = this.pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -230, 2, 2, pnlMenu);
        }else{
           Animacion.Animacion.mover_derecha(-230, 0, 2, 2, pnlMenu);

        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void UNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNOActionPerformed
        new CambiaPanel(pnlPrincipal, pnlUno());
        if(this.UNO.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(214,217,223));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(214,217,223));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
            
            
        }else{
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(204,204,204));
            this.UNO.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_UNOActionPerformed

    private void DOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOSActionPerformed
        new CambiaPanel(pnlPrincipal, pnlDos());
        if(this.DOS.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.DOS.setColorNormal( new Color(214,217,223));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_DOSActionPerformed

    private void UNOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UNOMousePressed
        this.UNO.setSelected(true);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_UNOMousePressed

    private void DOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOSMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(true);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_DOSMousePressed

    private void TRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRESActionPerformed
        new CambiaPanel(pnlPrincipal, pnlTres());
        if(this.TRES.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_TRESActionPerformed

    private void TRESMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TRESMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(true);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_TRESMousePressed

    private void CUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUATROActionPerformed
         new CambiaPanel(pnlPrincipal, pnlCuatro());
        if(this.CUATRO.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_CUATROActionPerformed

    private void CUATROMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CUATROMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(true);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_CUATROMousePressed

    private void CINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CINCOActionPerformed
        new CambiaPanel(pnlPrincipal, pnlCinco());
        if(this.CINCO.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_CINCOActionPerformed

    private void SEISMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEISMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(true);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_SEISMousePressed

    private void CINCOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CINCOMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(true);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_CINCOMousePressed

    private void SEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEISActionPerformed
        new CambiaPanel(pnlPrincipal, pnlSeis());
        if(this.CINCO.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_SEISActionPerformed

    private void SIETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIETEActionPerformed
      new CambiaPanel(pnlPrincipal, pnlSiste());
        if(this.SIETE.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_SIETEActionPerformed

    private void SIETEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIETEMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(true);
        this.OCHO.setSelected(false);
    }//GEN-LAST:event_SIETEMousePressed

    private void OCHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCHOActionPerformed
        new CambiaPanel(pnlPrincipal, pnlOcho());
        if(this.OCHO.isSelected()){
            this.UNO.setColorNormal( new Color(214,217,223));
            this.UNO.setColorHover( new Color(214,217,223));
            this.UNO.setColorPressed( new Color(214,217,223));
            
            this.DOS.setColorNormal( new Color(204,204,204));
            this.DOS.setColorHover( new Color(204,204,204));
            this.DOS.setColorPressed( new Color(204,204,204));
            
            this.TRES.setColorNormal( new Color(214,217,223));
            this.TRES.setColorHover( new Color(204,204,204));
            this.TRES.setColorPressed( new Color(214,217,223));
            
            this.CUATRO.setColorNormal( new Color(214,217,223));
            this.CUATRO.setColorHover( new Color(204,204,204));
            this.CUATRO.setColorPressed( new Color(214,217,223));
            
            this.CINCO.setColorNormal( new Color(214,217,223));
            this.CINCO.setColorHover( new Color(204,204,204));
            this.CINCO.setColorPressed( new Color(214,217,223));
            
            this.SEIS.setColorNormal( new Color(214,217,223));
            this.SEIS.setColorHover( new Color(204,204,204));
            this.SEIS.setColorPressed( new Color(214,217,223));
            
            this.SIETE.setColorNormal( new Color(214,217,223));
            this.SIETE.setColorHover( new Color(204,204,204));
            this.SIETE.setColorPressed( new Color(214,217,223));
            
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
            
        }else{
            this.OCHO.setColorNormal( new Color(214,217,223));
            this.OCHO.setColorHover( new Color(204,204,204));
            this.OCHO.setColorPressed( new Color(214,217,223));
        }
    }//GEN-LAST:event_OCHOActionPerformed

    private void OCHOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OCHOMousePressed
        this.UNO.setSelected(false);
        this.DOS.setSelected(false);
        this.TRES.setSelected(false);
        this.CUATRO.setSelected(false);
        this.CINCO.setSelected(false);
        this.SEIS.setSelected(false);
        this.SIETE.setSelected(false);
        this.OCHO.setSelected(true);
    }//GEN-LAST:event_OCHOMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro CINCO;
    private rsbuttom.RSButtonMetro CUATRO;
    private rsbuttom.RSButtonMetro DOS;
    private rsbuttom.RSButtonMetro OCHO;
    private rsbuttom.RSButtonMetro SEIS;
    private rsbuttom.RSButtonMetro SIETE;
    private rsbuttom.RSButtonMetro TRES;
    private rsbuttom.RSButtonMetro UNO;
    private rsbuttom.RSButtonMetro btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

    private JPanel pnlUno() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlDos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlTres() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlCuatro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlCinco() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlSeis() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlSiste() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private JPanel pnlOcho() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
